<!doctype>
<html>
  <head>
    <title>BypassNAT-test</title>
    <meta name="google-site-verification" content="CCFAuGwcZXEMpt4v_DYYzUJ-grO_j04rt8HWxYH_GJg" />
  </head>
  <body>
    {{ content }}
  </body>
</html>
